services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080
    container_name: bloodlink-client
    ports:
      - "3000:80"
    restart: always
